export const HATS_CONTRACT_ADDRESS = "0x3bc1A0Ad72417f2d411118085256fC53CBdDd137";
export const HSG_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_HSG_CONTRACT_ADDRESS;
export const HATS_TREE_ID = process.env.NEXT_PUBLIC_HATS_TREE_ID;
export const LEADER_HAT_ID = process.env.NEXT_PUBLIC_HATS_LEADER_ID;
export const LEADER_SAFE_ADDRESS = process.env.NEXT_PUBLIC_HATS_LEADER_SAFE_ACCOUNT;
export const INVITE_TTL_SECONDS = Number(process.env.INVITE_TTL_SECONDS || 86400);
