const en = {
  common: {
    welcome: "Welcome to the application!",
    submit: "Submit",
    cancel: "Cancel",
    copied: "Copied",
    unknown: "Unknown",
    login: "Login",
    logout: "Logout",
    loggingIn: "Logging in...",
    clickToCopyAddress: "Click to copy your RelayID",
    addressCopied: "RelayID copied to clipboard",
    accountDisconnected: "Account disconnected",
    loading: "Loading...",
    success: "Success",
    error: "Error",
    notAllowed: "Not allowed",
    allowed: "Allowed",
    copyLink: "Copy link",
    shareWhatsApp: "Share on WhatsApp",
    inviteExpires: "Invite link expires in 24 hours",
    generating: "Generating...",
    generateInvite: "Generate invite link",
    joinMe: "Join me on the RelayID Network! Use this invite link: ",
    failedToGenerate: "Failed to generate invite",
    failedToGenerateLink: "Failed to generate invite link",
    invalidAddress: "Invalid address: ",
    errorWhileScanning: "Error while scanning",
    unknownError: "An unknown error occurred",
    addLeader: "Add leader",
    addingLeader: "Adding leader...",
    sendingTx: "Sending ",
    transactionsPleaseWait: " transactions. Please keep this page open...",
    checkingPermissions: "Checking permissions...",
    theirAddress: "Their RelayID",
    inviteCopied: "Invite link copied to clipboard",
    copiedExclamation: "Copied!",
  },
  home: {
    title: "Home Page",
    description: "This is the home page of the application.",
  },
  profile: {
    myAccount: "My RelayID",
    relayIdTitle: "Your RelayID",
    relayIdDescription:
      "This is your unique RelayID that you can share with other leaders. They can use it to add you as a leader.",
  },
  status: {
    status: "Status",
    networkStatus: "Network Status",
    networkStatusDescription:
      "Your status shows whether you're connected to the RelayID network. To get onboarded, you'll need to be added by an existing network member.",
    onboardingTitle: "How to get onboarded",
    onboardingSteps: [
      "Share your RelayID with another leader",
      "They will need to add you to the network using your RelayID",
      "Once added, your status will update automatically",
    ],
    errorLoadingStatus: "Error loading status",
    youAreALeader: "You are a leader",
    notALeader: "Not a leader",
  },
  share: {
    shareAccountInfo: "Add me as a leader via",
    shareWithMembersTitle: "Share with other leaders",
    shareWithMembersDescription:
      "Share your RelayID with another leader to join the network. They can scan your QR code or use WhatsApp to get your RelayID.",
    whatsappShareMessage: "Please add me to the RelayID network: ",
  },
  qrCodeDialog: {
    shareQrCode: "Share QR Code",
    loginToViewQr: "Log in to view QR code",
    showQrInstruction: "Show this QR code to another community leader.",
    scanInstruction: "They can scan this code on the ",
    addLeaderPage: "Add Leader",
    pageSuffix: " page.",
  },
  header: {
    nav: {
      myAccount: "My RelayID",
      addLeader: "Add Leader",
      beneficiaries: "Beneficiaries",
    },
    menu: {
      open: "Open menu",
      close: "Close menu",
    },
  },
  page: {
    myAccountTitle: "My RelayID",
    loginPrompt: "Please log in to view your RelayID.",
    addAnotherLeader: "Add another leader",
    noPermission: "You don't have permission to add another leader.",
  },
  beneficiariesPage: {
    title: "Beneficiaries",
    loginPrompt: "Please log in to manage your beneficiaries.",
    checkingLeader: "Checking your leader status...",
    notLeader: "Only community leaders can add beneficiaries.",
    addHeading: "Add a beneficiary",
    addDescription:
      "Enter the beneficiary's Stellar account address (starts with G). You will be asked to sign, so the network knows the request is from you.",
    addressPlaceholder: "G…",
    invalidAddress: "Enter a valid Stellar account address (starts with G, 56 characters)",
    add: "Add beneficiary",
    adding: "Adding…",
    added: "Beneficiary added",
    listHeading: "My beneficiaries",
    listDescription:
      "Only you can see the beneficiaries you added. The first time, you sign in once; after that they load automatically.",
    show: "Show my beneficiaries",
    refresh: "Refresh",
    loadingList: "Loading…",
    empty: "You have not added any beneficiaries yet.",
    stellarAddress: "Stellar account",
    addedOn: "Added",
    allowanceHeading: "Your disbursement allowance",
    allowanceBalance: "Remaining",
    allowanceToday: "Used in the last 24 hours",
    allowanceLimits: (perDisbursement: string, perDay: string) =>
      `Up to ${perDisbursement} XLM per disbursement and ${perDay} XLM per 24 hours.`,
    amountLabel: "Amount (XLM)",
    disburse: "Disburse",
    disbursing: "Sending…",
    disbursed: "Disbursement created",
    disbursedDescription: (amount: string) =>
      `${amount} XLM is waiting for the beneficiary to redeem.`,
    amountRequired: "Enter an amount",
    invalidAmount: "Enter an amount such as 0.5 (up to 7 decimals)",
    amountPlaceholder: "XLM",
    recentHeading: "Recent disbursements",
    noDisbursements: "No disbursements yet.",
  },
  disbursements: {
    status: {
      pending: "Waiting to be redeemed",
      redeeming: "Being paid…",
      redeemed: "Paid",
      needs_review: "Being checked",
      cancelled: "Cancelled",
    },
    cancel: "Cancel",
    cancelling: "Cancelling…",
    cancelled: "Disbursement cancelled",
    cancelledDescription: (amount: string) => `${amount} XLM is back in your allowance.`,
    redeemTitle: "Redeem",
    redeemIntro:
      "If a community leader added your Stellar account, the XLM they sent you is waiting here. Connect your Stellar wallet (Freighter) to see and redeem it.",
    connect: "Connect Freighter",
    connecting: "Connecting…",
    connectedAs: "Stellar account",
    disconnect: "Disconnect",
    signInHint:
      "You will be asked to sign once with your Stellar wallet. It is free and does not move any money.",
    myHeading: "My disbursements",
    myDescription:
      "Funds that a community leader has sent you. Redeem them to receive the XLM in your Stellar wallet.",
    show: "Show my disbursements",
    refresh: "Refresh",
    loading: "Loading…",
    none: "You have no disbursements.",
    redeem: "Redeem",
    redeeming: "Redeeming… this can take up to a minute",
    redeemed: "Redeemed",
    redeemedDescription: (amount: string) => `${amount} XLM was sent to your Stellar wallet.`,
    viewTransaction: "View transaction",
  },
  addPage: {
    headings: {
      addLeaderToNetwork: "Add leader to the network",
      addLeaderToNetworkShort: "Add leader to network",
      sendInviteLink: "Send invite link",
    },
    prompts: {
      loginToAdd: "Please log in to add a leader.",
      two: "two",
      singleUseInvite: "This invite link can only be used for one successful onboarding.",
      reservationInfo:
        "When a user opens this invite link, it will be reserved for them for a limited time.",
      notAllowed: "You are not allowed to add leaders to the network.",
      getBadge: "Get your leadership badge from another leader.",
    },
    toasts: {
      successAdded: "Successfully added leader ",
      errorAdding: "Error adding leader:",
      errorQr: "Error in QR code",
    },
  },
  invitePage: {
    headings: {
      success: "Success!",
      verifying: "Verifying invite...",
      invalid: "Invalid Invite",
      accept: "Accept Invite",
      alreadyOnboarded: "Already Onboarded",
      expired: "Invite Expired",
      used: "Invite Already Used",
      reserved: "Invite In Use",
      error: "Error",
    },
    prompts: {
      onboarded: "You have been successfully onboarded as a leader!",
      viewAccount: "View your RelayID",
      invalid: "This invite is no longer valid.",
      login: "Please login or sign up to be accepted as a leader.",
      accept: "Please accept the invite to join the Relay Network as a leader.",
      processing: "Processing...",
      acceptInvite: "Accept Invite",
      reserved:
        "This invite is currently being used. Please try again later or request a new invite.",
      singleUse: "This invite link can only be used once.",
      alreadyOnboarded:
        "The connected account is already onboarded and cannot use this invite link.",
      checkingWalletStatus: "Checking account status…",
      expired: "Please request a new invite from another leader.",
      used: "This invite has already been used.",
      error: "Something went wrong. Please try again later.",
    },
    toasts: {
      errorAccepting: "Error accepting invite:",
      failedToAccept: "Failed to accept invite",
    },
  },
};

export default en;
